### ISSUE TITLE
chef-client fails when specifying rules that are not tcp/udp specific

### ISSUE THREAD

**Issue by GregAndo** [biola/chef-netsh_firewall#1]
You've made a great start here, but there are some flaws I have identified.

When specifying a TCP or UDP rule, they usually work.  However when it comes to specifying and ICMPv4 rule or a rule for "protocol :any" the chef-client run will fail, stating:

"Ports can only be specified if the protocol is TCP or UDP."

We need some logic that will not specify the argument "localport" or "remoteport" to netsh in these cases.

**Comment by kingjared** [comment]
Just confirmed this in test-kitchen. I'll roll out a fix for this soon.

**Comment by kingjared** [comment]
Fixed with commit 8efa85a9dbde945b92f70b54de1158ebe9b2d5ea

**Comment by GregAndo** [comment]
Nice work on this one.  I did mean to thank you for your prompt work.  Well done!
